dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_install: 
  - cd backend
before_script:
  - mysql -e 'CREATE DATABASE igdb;'
after_success:
  - bash <(curl -s https://codecov.io/bash)
