dist: trusty
language: java
jdk:
  - oraclejdk8
 services:
  - mysql
before_install: 
  - mysql -e 'CREATE DATABASE IF NOT EXISTS igdb;'
  -cd backend
after_success:
  - bash <(curl -s https://codecov.io/bash)
